---
- name: Wait for ssh to come up
  hosts: "{{ instance_name }}"
  become: false
  gather_facts: no

  tasks:
    - wait_for_connection:
        delay: 15
        timeout: 180  

- name: Build and Test Go Application
  hosts: "{{ instance_name }}"
  become: false
  gather_facts: yes

  tasks:
  - import_role:
      name: go-deploy
