---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: hello-repo
spec:
  type: git
  params:
    - name: url
      value: https://github.com/ktenzer/go-hello-world.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: hello-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/go-hello-world/hello:latest
